id: P466DD49E
initial_creation_type: input
source_metadata:
  Title: Gilgit Manuscripts
  Editor: Dutta, Nalinaksa
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi
  Year: '1984'
  1 bhaiṣajyavastu:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  2 cīvaravastu:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  3 kaṭhinavastu:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  5 karmavastu:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  4 kośāmbakavastu:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:16:14.252669'
last_modified_at: '2022-03-08T16:16:14.252680'
